spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlserver://192.168.1.204:1433;databaseName=TRENDYT_SCHOOL_DB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  secretKey: fabeb0e18109414e9ab81b9dba8f88c341bbc9e6edf3db132df0a18be2557e39
  refreshKey: 6qs0ii6phyyaI3MlO5aQ8/D/RBJcQKGxMFuBdfwC+Qw=
  expiryHour: 1
  expiryDay: 14