spring:
  profiles:
    active: dev

################### Data Host ########################
#  datasource:
#    url: jdbc:sqlserver://SQL8020.site4now.net;databaseName=db_aac186_trendyt002;user=db_aac186_trendyt002_admin;password=trendyt002;encrypt=true;trustServerCertificate=true
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

################### Data Local ########################
#  datasource:
#    url: jdbc:sqlserver://localhost:1444;databaseName=TRENDYT_SCHOOL_DB;encrypt=true;trustServerCertificate=true
#    username: SA
#    password: Tung2003#
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=TRENDYT_SCHOOL_DB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: dev
jwt:
  secretKey: fabeb0e18109414e9ab81b9dba8f88c341bbc9e6edf3db132df0a18be2557e39
  expiryHour: 1
  expiryDay: 14